CREATE TABLE `customer` (
    `id` int NOT NULL AUTO_INCREMENT,
    `customer_no` char(40) NOT NULL,
    `org_no` char(20) NOT NULL,
    `vat_no` char(20) DEFAULT NULL,
    `name` varchar(50) NOT NULL,
    `refactoring` int NOT NULL DEFAULT "0",
    -- `address1` varchar(45) DEFAULT NULL,
    -- `address2` varchar(45) DEFAULT NULL,
    `zip` varchar(10) NOT NULL DEFAULT '0001',
    `city` varchar(45) NOT NULL DEFAULT 'IKKE SATT',
    -- `billing_address1` varchar(45) DEFAULT NULL,
    -- `billing_address2` varchar(45) DEFAULT NULL,
    `billing_zip` varchar(10) DEFAULT NULL,
    `billing_city` varchar(45) DEFAULT NULL,
    `customer_status` int DEFAULT '0',
    `use_alt_pdf_front` int NOT NULL DEFAULT '0',
    `recieve_mail` int NOT NULL DEFAULT '0',
    `mail_template` varchar(255) DEFAULT NULL,
    `mail_color_scheme` varchar(255) DEFAULT NULL,
    `customer_head_id` int DEFAULT NULL,
    `admin_cost_per_cost_object` int NOT NULL DEFAULT "0",
    `mail_template_department` varchar(255) DEFAULT NULL,
    `comment` text,
    `invoice_quantity` int NOT NULL DEFAULT '0',
    `invoice_cost` decimal(8, 2) NOT NULL DEFAULT '0.00',
    `init_arpu` decimal(8, 2) NOT NULL DEFAULT '0.00',
    `init_uarpu` decimal(8, 2) NOT NULL DEFAULT '0.00',
    `init_barpu` decimal(8, 2) NOT NULL DEFAULT '0.00',
    `country_id` int NOT NULL DEFAULT '47',
    `locale` varchar(2) DEFAULT NULL,
    `whitelabel_id` int NOT NULL DEFAULT '1',
    `department_mail_send_date` smallint DEFAULT NULL,
    `tci_index_percentage` decimal(10, 2) NOT NULL DEFAULT '25.00',
    `salary_deduct_app_mail_template` varchar(255) DEFAULT NULL,
    `customer_custom_url_param` varchar(255) DEFAULT NULL,
    `mail_template_admin` varchar(255) DEFAULT NULL,
    `mail_template_user_reminder` varchar(255) DEFAULT NULL,
    `dealer_user_id` int DEFAULT NULL,
    `device_dealer_user_id` int DEFAULT NULL,
    `device_policy_message` text,
    `created` datetime DEFAULT NULL,
    `last_update` datetime DEFAULT NULL,
    `billing_cycle_months` int NOT NULL DEFAULT '1',
    `device_policy_vendor_id` int DEFAULT '1',
    `number_of_employees` int DEFAULT NULL,
    `internal_company_identifier` varchar(45) DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_customers_org_no` (`org_no`),
    UNIQUE KEY `customer_no_UNIQUE` (`customer_no`),
    KEY `customer_whitelabel` (`whitelabel_id`),
    KEY `customer_head_id` (`customer_head_id`),
    KEY `country_id` (`country_id`),
    KEY `customer_device_policy_vendor_id_index` (`device_policy_vendor_id`)
) ENGINE = InnoDB AUTO_INCREMENT = 1001035 DEFAULT CHARSET = utf8mb3;