CREATE TABLE `device_policy` (
    `id` int NOT NULL AUTO_INCREMENT,
    `customer_id` int DEFAULT NULL,
    `name` varchar(255) NOT NULL,
    `description` text NOT NULL,
    `covered_amount` decimal(12, 2) NOT NULL DEFAULT '0.00',
    `cover_interval` int NOT NULL DEFAULT '0' COMMENT 'months passed for full cover',
    `minimum_amount` decimal(12, 2) NOT NULL DEFAULT '0.00',
    `order_interval` int NOT NULL DEFAULT '0' COMMENT 'months between possible purchases',
    `payment_interval` int NOT NULL DEFAULT '3' COMMENT 'amount (months) of downpayment when not instant',
    `manager_approval_needed` tinyint(1) NOT NULL DEFAULT '0',
    `customer_head_id` int DEFAULT NULL,
    `vat` tinyint(1) DEFAULT '0',
    `is_custom_address_activated` tinyint(1) DEFAULT '0',
    `auto_add_new_products` tinyint(1) NOT NULL DEFAULT '1',
    `admin_user_id` int DEFAULT NULL,
    `is_active` tinyint DEFAULT '1',
    PRIMARY KEY (`id`),
    KEY `customer_id` (`customer_id`),
    KEY `device_policy_customer_head_id_index` (`customer_head_id`),
    KEY `device_policy_customer_id_index` (`customer_id`),
    KEY `device_policy_user_id_fk` (`admin_user_id`),
    CONSTRAINT `device_policy_customer_head_id_fk` FOREIGN KEY (`customer_head_id`) REFERENCES `customer_head` (`id`) ON DELETE CASCADE,
    CONSTRAINT `device_policy_customer_id_fk` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`id`) ON DELETE CASCADE,
    CONSTRAINT `device_policy_user_id_fk` FOREIGN KEY (`admin_user_id`) REFERENCES `user` (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 155205 DEFAULT CHARSET = utf8mb3;