CREATE TABLE `user` (
    `id` int NOT NULL AUTO_INCREMENT,
    `usergroup_id` int NOT NULL,
    `customer_id` int DEFAULT NULL,
    `username` varchar(100) DEFAULT NULL,
    `password` varchar(256) DEFAULT NULL,
    `first_name` varchar(50) NOT NULL,
    `last_name` varchar(50) NOT NULL,
    `email` varchar(255) NOT NULL,
    `phone_number` varchar(45) DEFAULT NULL,
    `reset_token` varchar(50) DEFAULT NULL,
    `reset_timeout` datetime DEFAULT NULL,
    `invoice_account_id` int DEFAULT NULL,
    `seller` int NOT NULL DEFAULT '0',
    `salesboss` int NOT NULL DEFAULT '0',
    `country_id` int NOT NULL DEFAULT '47',
    `locale` varchar(2) DEFAULT NULL,
    `inactive` int NOT NULL DEFAULT '0',
    `email_cc` varchar(255) DEFAULT NULL,
    `email_bcc` varchar(255) DEFAULT NULL,
    `adminsecretcode` varchar(256) DEFAULT NULL,
    `has_frame_agreement_access` tinyint(1) DEFAULT '0',
    `is_i18n_admin` tinyint(1) DEFAULT '0',
    `is_password_change_required` tinyint DEFAULT '0',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_user_username` (`username`),
    KEY `fk_user_customer` (`customer_id`),
    KEY `fk_user_usergroup_idx` (`usergroup_id`),
    KEY `fk_user_invoice_account` (`invoice_account_id`),
    KEY `user_phone_number_index` (`phone_number`),
    CONSTRAINT `fk_user_invoice_account` FOREIGN KEY (`invoice_account_id`) REFERENCES `invoice_account` (`id`),
    CONSTRAINT `fk_user_usergroup` FOREIGN KEY (`usergroup_id`) REFERENCES `usergroup` (`id`),
    CONSTRAINT `fk_users_customers` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB AUTO_INCREMENT = 9080 DEFAULT CHARSET = utf8mb3;