CREATE TABLE user (
    id int auto_increment primary key,
    usergroup_id int not null,
    customer_id int null,
    username varchar(100) null,
    password varchar(256) null,
    first_name varchar(50) not null,
    last_name varchar(50) not null,
    email varchar(255) not null,
    phone_number varchar(45) null,
    reset_token varchar(50) null,
    reset_timeout datetime null,
    invoice_account_id int null,
    seller int not null,
    salesboss int not null,
    country_id int default 47 not null,
    locale varchar(2) null,
    inactive int not null,
    email_cc varchar(255) null,
    email_bcc varchar(255) null,
    adminsecretcode varchar(256) null,
    has_frame_agreement_access tinyint(1) default 0 null,
    constraint uk_user_username unique (username),
    constraint fk_user_invoice_account foreign key (invoice_account_id) references control.invoice_account (id),
    constraint fk_user_usergroup foreign key (usergroup_id) references control.usergroup (id),
    constraint fk_users_customers foreign key (customer_id) references control.customer (id) on delete cascade
) charset = utf8mb3;